import {useEffect,useState} from 'react';
import {LinearGradient} from 'expo-linear-gradient';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {router} from 'expo-router';
import {colors,shadow} from '@/src/theme';
import {supabase} from '@/src/lib/supabase';

export default function Admin(){
 const[workspaceId,setWorkspaceId]=useState<string|null>(null);const[members,setMembers]=useState<any[]>([]);const[requests,setRequests]=useState<any[]>([]);const[allowed,setAllowed]=useState<boolean|null>(null);const[error,setError]=useState('');
 const load=async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const wm=await supabase.from('workspace_members').select('workspace_id,role').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();if(!wm.data||wm.data.role!=='admin'){setAllowed(false);return}setAllowed(true);setWorkspaceId(wm.data.workspace_id);const[mr,rr]=await Promise.all([supabase.from('workspace_members').select('role,profile:profiles(id,full_name,email,avatar_url,status)').eq('workspace_id',wm.data.workspace_id).eq('status','active'),supabase.from('join_requests').select('id,user_id,email,requested_name,status,created_at').eq('workspace_id',wm.data.workspace_id).eq('status','pending').order('created_at',{ascending:false})]);if(mr.error)setError(mr.error.message);else setMembers(mr.data||[]);if(!rr.error)setRequests(rr.data||[])};useEffect(()=>{load()},[]);
 const approve=async(r:any)=>{if(!workspaceId)return;const ins=await supabase.from('workspace_members').upsert({workspace_id:workspaceId,user_id:r.user_id,role:'member',status:'active'});if(ins.error){setError(ins.error.message);return}await supabase.from('join_requests').update({status:'approved',reviewed_at:new Date().toISOString()}).eq('id',r.id);load()};
 if(allowed===false)return <View style={s.center}><Text style={s.big}>🔒</Text><Text style={s.title}>Admin access required</Text><Text style={s.sub}>Only workspace admins can manage members.</Text><Pressable onPress={()=>router.back()} style={s.primary}><Text style={s.primaryText}>Back to chat</Text></Pressable></View>;
 if(allowed===null)return <View style={s.center}><Text style={s.sub}>Loading workspace controls…</Text></View>;
 return <View style={s.root}><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Text>←</Text></Pressable><View><Text style={s.kicker}>WORKSPACE ADMIN</Text><Text style={s.title}>Manage the crew ⚡</Text></View><View style={s.adminPill}><Text style={s.adminPillText}>ADMIN</Text></View></View><ScrollView contentContainerStyle={s.content}><LinearGradient colors={['#EAF9FF','#F5EEFF']} style={s.hero}><Text style={s.heroEmoji}>🫶</Text><View style={{flex:1}}><Text style={s.heroTitle}>Bookairfreight HQ</Text><Text style={s.heroSub}>Approve join requests and manage real workspace membership.</Text></View></LinearGradient><View style={s.actions}><Pressable onPress={()=>router.push('/signup')} style={s.secondary}><Text style={s.secondaryText}>Share signup</Text></Pressable></View>{error?<Text style={s.error}>{error}</Text>:null}<Text style={s.section}>PENDING REQUESTS · {requests.length}</Text>{requests.length===0?<View style={s.empty}><Text style={s.emptyTitle}>No pending requests</Text><Text style={s.emptyText}>New signups will appear here for approval.</Text></View>:requests.map(r=><View key={r.id} style={s.member}><View style={s.avatar}><Text style={s.avatarText}>{r.requested_name.trim().split(/\s+/).map((x:string)=>x[0]).join('').slice(0,2).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.memberName}>{r.requested_name}</Text><Text style={s.email}>{r.email}</Text></View><Pressable onPress={()=>approve(r)} style={s.approve}><Text style={s.approveText}>Approve</Text></Pressable></View>)}<Text style={s.section}>ACTIVE MEMBERS · {members.length}</Text>{members.map((m:any)=><View key={m.profile.id} style={s.member}><View style={s.avatar}><Text style={s.avatarText}>{m.profile.full_name.trim().split(/\s+/).map((x:string)=>x[0]).join('').slice(0,2).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.memberName}>{m.profile.full_name}</Text><Text style={s.email}>{m.profile.email||'No email'}</Text></View><View style={[s.roleBadge,m.role==='admin'&&s.adminBadge]}><Text style={s.roleBadgeText}>{m.role}</Text></View></View>)}</ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},center:{flex:1,justifyContent:'center',alignItems:'center',padding:25,backgroundColor:colors.bg},big:{fontSize:42},head:{padding:22,paddingTop:28,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:colors.border,backgroundColor:'#fff'},back:{width:38,height:38,borderRadius:13,backgroundColor:'#F1F6FF',alignItems:'center',justifyContent:'center'},kicker:{fontSize:8,fontWeight:'900',letterSpacing:2.5,color:colors.cyan},title:{fontSize:24,fontWeight:'900',color:colors.ink,marginTop:3},sub:{fontSize:12,color:colors.muted,marginTop:7,textAlign:'center'},adminPill:{marginLeft:'auto',backgroundColor:colors.pink,paddingHorizontal:10,paddingVertical:6,borderRadius:10},adminPillText:{fontSize:8,fontWeight:'900',color:colors.ink},content:{width:'100%',maxWidth:900,alignSelf:'center',padding:22,paddingBottom:60},hero:{padding:20,borderRadius:22,flexDirection:'row',alignItems:'center',gap:14},heroEmoji:{fontSize:34},heroTitle:{fontSize:17,fontWeight:'900',color:colors.ink},heroSub:{fontSize:11,color:colors.muted,marginTop:4},actions:{flexDirection:'row',gap:10,marginTop:16},secondary:{height:46,borderRadius:14,paddingHorizontal:18,backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},secondaryText:{fontSize:11,fontWeight:'900',color:colors.blue},section:{fontSize:9,fontWeight:'900',letterSpacing:2.5,color:colors.blue,marginTop:24,marginBottom:9},member:{padding:13,borderRadius:17,backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:12,marginBottom:8},avatar:{width:44,height:44,borderRadius:14,backgroundColor:'#DDEBFF',alignItems:'center',justifyContent:'center'},avatarText:{fontSize:12,fontWeight:'900',color:colors.blue},memberName:{fontSize:12,fontWeight:'900',color:colors.ink},email:{fontSize:9,color:colors.muted,marginTop:3},roleBadge:{paddingHorizontal:9,paddingVertical:6,borderRadius:9,backgroundColor:'#EEF3F8'},adminBadge:{backgroundColor:'#FCE7F0'},roleBadgeText:{fontSize:8,fontWeight:'900',color:colors.ink},approve:{paddingHorizontal:12,paddingVertical:8,borderRadius:10,backgroundColor:colors.blue},approveText:{fontSize:9,fontWeight:'900',color:'#fff'},empty:{padding:18,borderRadius:17,backgroundColor:'#fff',borderWidth:1,borderColor:colors.border},emptyTitle:{fontSize:12,fontWeight:'900',color:colors.ink},emptyText:{fontSize:10,color:colors.muted,marginTop:4},primary:{marginTop:18,height:46,borderRadius:14,paddingHorizontal:18,backgroundColor:colors.blue,alignItems:'center',justifyContent:'center'},primaryText:{fontSize:11,fontWeight:'900',color:'#fff'},error:{fontSize:10,color:'#C94A75',marginTop:10}});