import {useState} from 'react';
import {LinearGradient} from 'expo-linear-gradient';
import {Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {router} from 'expo-router';
import {colors,shadow} from '@/src/theme';

const starter=[['Aarthi Rajendran','aarthi@bookairfreight.com','Admin','AR'],['Daisy','daisy@bookairfreight.com','Admin','DA'],['Inderjith','inderjith@bookairfreight.com','Admin','IN'],['Creative Team','creative@bookairfreight.com','Member','CT']];
export default function Admin(){
 const [members,setMembers]=useState(starter); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [role,setRole]=useState('Member'); const [showAdd,setShowAdd]=useState(false);
 const add=()=>{if(!name.trim()||!email.trim())return;const initials=name.trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();setMembers(m=>[...m,[name.trim(),email.trim(),role,initials]]);setName('');setEmail('');setShowAdd(false)};
 return <View style={s.root}><View style={s.head}><Pressable onPress={()=>router.back()} style={s.back}><Text>←</Text></Pressable><View><Text style={s.kicker}>WORKSPACE ADMIN</Text><Text style={s.title}>Manage the crew ⚡</Text></View><View style={s.adminPill}><Text style={s.adminPillText}>ADMIN</Text></View></View><ScrollView contentContainerStyle={s.content}><LinearGradient colors={['#EAF9FF','#F5EEFF']} style={s.hero}><Text style={s.heroEmoji}>🫶</Text><View style={{flex:1}}><Text style={s.heroTitle}>Bookairfreight HQ</Text><Text style={s.heroSub}>Invite people, control roles and keep the workspace tidy.</Text></View></LinearGradient><View style={s.actions}><Pressable onPress={()=>setShowAdd(v=>!v)} style={s.primary}><Text style={s.primaryText}>＋ Add member</Text></Pressable><Pressable onPress={()=>router.push('/signup')} style={s.secondary}><Text style={s.secondaryText}>Share signup</Text></Pressable></View>{showAdd&&<View style={s.form}><Text style={s.formTitle}>Add a teammate</Text><TextInput value={name} onChangeText={setName} placeholder="Full name" placeholderTextColor={colors.muted} style={s.input}/><TextInput value={email} onChangeText={setEmail} placeholder="Work email" placeholderTextColor={colors.muted} autoCapitalize="none" style={s.input}/><View style={s.roles}>{['Member','Admin'].map(r=><Pressable key={r} onPress={()=>setRole(r)} style={[s.role,role===r&&s.roleActive]}><Text style={[s.roleText,role===r&&s.roleTextActive]}>{r}</Text></Pressable>)}</View><Pressable onPress={add} style={s.primary}><Text style={s.primaryText}>Create member</Text></Pressable></View>}<Text style={s.section}>MEMBERS · {members.length}</Text>{members.map((m,i)=><View key={m[1]} style={s.member}><View style={s.avatar}><Text style={s.avatarText}>{m[3]}</Text></View><View style={{flex:1}}><Text style={s.memberName}>{m[0]}</Text><Text style={s.email}>{m[1]}</Text></View><View style={[s.roleBadge,m[2]==='Admin'&&s.adminBadge]}><Text style={s.roleBadgeText}>{m[2]}</Text></View></View>)}</ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},head:{padding:22,paddingTop:28,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:colors.border,backgroundColor:'#fff'},back:{width:38,height:38,borderRadius:13,backgroundColor:'#F1F6FF',alignItems:'center',justifyContent:'center'},kicker:{fontSize:8,fontWeight:'900',letterSpacing:2.5,color:colors.cyan},title:{fontSize:24,fontWeight:'900',color:colors.ink,marginTop:3},adminPill:{marginLeft:'auto',backgroundColor:'#F4A7C7',paddingHorizontal:10,paddingVertical:6,borderRadius:10},adminPillText:{fontSize:8,fontWeight:'900',color:colors.ink},content:{width:'100%',maxWidth:900,alignSelf:'center',padding:22,paddingBottom:60},hero:{padding:20,borderRadius:22,flexDirection:'row',alignItems:'center',gap:14},heroEmoji:{fontSize:34},heroTitle:{fontSize:17,fontWeight:'900',color:colors.ink},heroSub:{fontSize:11,color:colors.muted,marginTop:4},actions:{flexDirection:'row',gap:10,marginTop:16},primary:{height:46,borderRadius:14,paddingHorizontal:18,backgroundColor:colors.blue,alignItems:'center',justifyContent:'center'},primaryText:{fontSize:11,fontWeight:'900',color:'#fff'},secondary:{height:46,borderRadius:14,paddingHorizontal:18,backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},secondaryText:{fontSize:11,fontWeight:'900',color:colors.blue},form:{marginTop:14,padding:18,borderRadius:20,backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,...shadow},formTitle:{fontSize:16,fontWeight:'900',color:colors.ink,marginBottom:8},input:{height:46,borderWidth:1,borderColor:colors.border,borderRadius:13,paddingHorizontal:13,color:colors.ink,marginTop:8,backgroundColor:'#FAFCFF'},roles:{flexDirection:'row',gap:8,marginTop:10},role:{paddingHorizontal:14,paddingVertical:9,borderRadius:10,backgroundColor:'#F1F5FA'},roleActive:{backgroundColor:'#E9E9FF'},roleText:{fontSize:10,fontWeight:'800',color:colors.muted},roleTextActive:{color:colors.blue},section:{fontSize:9,fontWeight:'900',letterSpacing:2.5,color:colors.blue,marginTop:24,marginBottom:9},member:{padding:13,borderRadius:17,backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:12,marginBottom:8},avatar:{width:44,height:44,borderRadius:14,backgroundColor:'#DDEBFF',alignItems:'center',justifyContent:'center'},avatarText:{fontSize:12,fontWeight:'900',color:colors.blue},memberName:{fontSize:12,fontWeight:'900',color:colors.ink},email:{fontSize:9,color:colors.muted,marginTop:3},roleBadge:{paddingHorizontal:9,paddingVertical:6,borderRadius:9,backgroundColor:'#EEF3F8'},adminBadge:{backgroundColor:'#FCE7F0'},roleBadgeText:{fontSize:8,fontWeight:'900',color:colors.ink}});