import {useState} from 'react';
import {LinearGradient} from 'expo-linear-gradient';
import {Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {router} from 'expo-router';
import {colors,shadow} from '@/src/theme';

export default function Signup(){
 const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [done,setDone]=useState(false);
 return <LinearGradient colors={['#F2FBFF','#F8F3FF','#FFF8FB']} style={s.root}>
  <View style={s.card}>
   <View style={s.logo}><Text style={s.logoText}>BAF</Text></View>
   <Text style={s.kicker}>BOOKAIRFREIGHT · TEAM CHAT</Text>
   <Text style={s.title}>Join the crew ✨</Text>
   <Text style={s.sub}>Create your team profile. Your photo is optional — if you skip it, your initials will appear automatically.</Text>
   {done?<View style={s.success}><Text style={s.successEmoji}>🎉</Text><Text style={s.successTitle}>Request received</Text><Text style={s.successText}>An admin can approve and add you to the workspace.</Text><Pressable onPress={()=>router.replace('/(tabs)/chats')} style={s.primary}><Text style={s.primaryText}>Back to chat</Text></Pressable></View>:<><Text style={s.label}>FULL NAME</Text><TextInput value={name} onChangeText={setName} placeholder="Your name" placeholderTextColor={colors.muted} style={s.input}/><Text style={s.label}>WORK EMAIL</Text><TextInput value={email} onChangeText={setEmail} placeholder="name@bookairfreight.com" placeholderTextColor={colors.muted} autoCapitalize="none" keyboardType="email-address" style={s.input}/><Text style={s.label}>PROFILE PHOTO · OPTIONAL</Text><Pressable style={s.photo}><Text style={s.photoInitials}>{name.trim()?name.trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase():'AR'}</Text><View><Text style={s.photoTitle}>Add profile photo</Text><Text style={s.photoSub}>Without one, your initials stay embedded.</Text></View></Pressable><Pressable disabled={!name.trim()||!email.trim()} onPress={()=>setDone(true)} style={[s.primary,(!name.trim()||!email.trim())&&s.disabled]}><Text style={s.primaryText}>Request access →</Text></Pressable><Pressable onPress={()=>router.back()}><Text style={s.back}>Already have access? Sign in</Text></Pressable></>}
  </View>
 </LinearGradient>
}
const s=StyleSheet.create({root:{flex:1,justifyContent:'center',alignItems:'center',padding:20},card:{width:'92%',maxWidth:520,backgroundColor:'#fff',borderRadius:30,padding:28,borderWidth:1,borderColor:colors.border,...shadow},logo:{width:54,height:54,borderRadius:17,backgroundColor:'#EEF7FF',alignItems:'center',justifyContent:'center'},logoText:{fontSize:13,fontWeight:'900',letterSpacing:1,color:colors.blue},kicker:{fontSize:8,fontWeight:'900',letterSpacing:2.3,color:colors.cyan,marginTop:18},title:{fontSize:30,fontWeight:'900',color:colors.ink,marginTop:6},sub:{fontSize:12,lineHeight:19,color:colors.muted,marginTop:8,marginBottom:20},label:{fontSize:8,fontWeight:'900',letterSpacing:2,color:colors.blue,marginTop:12,marginBottom:6},input:{height:48,borderWidth:1,borderColor:colors.border,borderRadius:14,paddingHorizontal:14,color:colors.ink,backgroundColor:'#FAFCFF'},photo:{marginTop:7,padding:11,borderRadius:16,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:12},photoInitials:{width:44,height:44,borderRadius:14,backgroundColor:colors.violet,overflow:'hidden',textAlign:'center',textAlignVertical:'center',fontSize:13,fontWeight:'900',color:'#fff'},photoTitle:{fontSize:11,fontWeight:'900',color:colors.ink},photoSub:{fontSize:9,color:colors.muted,marginTop:3},primary:{height:50,borderRadius:16,backgroundColor:colors.blue,alignItems:'center',justifyContent:'center',marginTop:18},primaryText:{fontSize:12,fontWeight:'900',color:'#fff'},disabled:{opacity:.45},back:{fontSize:11,fontWeight:'800',color:colors.blue,textAlign:'center',marginTop:14},success:{alignItems:'center',paddingVertical:18},successEmoji:{fontSize:45},successTitle:{fontSize:20,fontWeight:'900',color:colors.ink,marginTop:8},successText:{fontSize:12,color:colors.muted,textAlign:'center',marginTop:5}});