import {useEffect,useRef} from 'react';
import {Animated,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {LinearGradient} from 'expo-linear-gradient';
import {Ionicons} from '@expo/vector-icons';
import {router} from 'expo-router';
import {colors,gradients,shadow} from '@/src/theme';
const channels=[['general','Team HQ','👋','8'],['marketing','Marketing','✨','5'],['outreach','Outbound squad','🚀','12'],['campaigns','Campaigns','🎯','3'],['random','Random','🪩','']];
const dms=[['Aarthi Rajendran','Online','AR','💬'],['Eli','Away','EL','🔥'],['Creative Team','3 members','CT','🎨']];
export default function Chats(){const pulse=useRef(new Animated.Value(0)).current;useEffect(()=>{Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1,duration:1100,useNativeDriver:true}),Animated.timing(pulse,{toValue:0,duration:1100,useNativeDriver:true})])).start()},[]);return <View style={s.root}><LinearGradient colors={gradients.soft} style={s.hero}><View><Text style={s.kicker}>BAF CHAT</Text><Text style={s.title}>Your team, but louder. ✨</Text><Text style={s.sub}>Fast conversations, chaotic energy, zero corporate beige.</Text></View><Animated.View style={{transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[1,1.12]})}]}}><LinearGradient colors={gradients.main} style={s.avatar}><Text style={s.avatarText}>IN</Text></LinearGradient></Animated.View></LinearGradient><ScrollView contentContainerStyle={s.scroll}><Text style={s.section}>CHANNELS</Text>{channels.map(([id,name,emoji,count])=><Pressable key={id} onPress={()=>router.push('/channel/'+id as any)} style={({pressed})=>[s.row,pressed&&{transform:[{scale:.985}]}]}><View style={s.icon}><Text>{emoji}</Text></View><View style={{flex:1}}><Text style={s.name}># {name}</Text><Text style={s.preview}>{id==='general'?'The team lounge':id==='marketing'?'Ideas, launches & trends':id==='outreach'?'Prospects, replies & wins':id==='campaigns'?'Campaign drops & experiments':'Memes belong here.'}</Text></View>{count?<View style={s.badge}><Text style={s.badgeText}>{count}</Text></View>:<Ionicons name="chevron-forward" size={18} color={colors.muted}/>}</Pressable>)}<Text style={[s.section,{marginTop:24}]}>DIRECT MESSAGES</Text>{dms.map(([id,status,initials,emoji])=><Pressable key={id} onPress={()=>router.push('/dm/'+encodeURIComponent(id) as any)} style={s.row}><View style={s.person}><Text style={s.personText}>{initials}</Text><View style={s.dot}/></View><View style={{flex:1}}><Text style={s.name}>{id}</Text><Text style={s.preview}>{status} · Tap to chat</Text></View><Text style={{fontSize:20}}>{emoji}</Text></Pressable>)}</ScrollView></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},hero:{paddingHorizontal:22,paddingTop:62,paddingBottom:22,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomLeftRadius:30,borderBottomRightRadius:30},kicker:{fontSize:11,fontWeight:'900',letterSpacing:4,color:colors.cyan},title:{fontSize:25,fontWeight:'900',color:colors.ink,marginTop:5},sub:{fontSize:12,color:colors.muted,marginTop:5,maxWidth:285},avatar:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center',...shadow},avatarText:{color:'#fff',fontWeight:'900'},scroll:{padding:20,paddingBottom:100},section:{fontSize:10,fontWeight:'900',letterSpacing:3,color:colors.blue,marginBottom:10},row:{backgroundColor:'rgba(255,255,255,.88)',borderWidth:1,borderColor:colors.border,borderRadius:20,padding:14,marginBottom:9,flexDirection:'row',alignItems:'center',...shadow},icon:{width:42,height:42,borderRadius:14,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center',marginRight:13},name:{fontSize:15,fontWeight:'900',color:colors.ink},preview:{fontSize:11,color:colors.muted,marginTop:3},badge:{backgroundColor:colors.blue,borderRadius:12,paddingHorizontal:9,paddingVertical:5},badgeText:{color:'#fff',fontSize:10,fontWeight:'900'},person:{width:42,height:42,borderRadius:15,backgroundColor:'#E5EDFF',alignItems:'center',justifyContent:'center',marginRight:13,position:'relative'},personText:{fontWeight:'900',color:colors.blue},dot:{position:'absolute',right:-1,bottom:-1,width:11,height:11,borderRadius:6,backgroundColor:'#49D17D',borderWidth:2,borderColor:'#fff'}});
